using System.Text;

namespace Cranks.SeedWork.Domain.Generator.Extensions;

internal static class CodeGenerationExtensions
{
    public static StringBuilder AppendFileHeader(this StringBuilder code)
    {
        return code.AppendLine("// <auto-generated />")
                   .AppendLine("#nullable enable")
                   .AppendLine();
    }

    public static StringBuilder AppendNamespace(this StringBuilder code, bool isGlobalNamespace, string? ns)
    {
        return isGlobalNamespace
                   ? code
                   : code.AppendLine($"namespace {ns};")
                         .AppendLine();
    }
}
